### ISSUE TITLE
Wrong name for "PlayOff" scheme

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#111]
When you create a tournament you should see "PlayOff" instead of "4" when selecting Scheme

- [x] #155 - Find all related with this task data

- [x] #156  - Fix the problem with wrong name for "Play off" scheme

- [x] #157  - Testing result of work
