### ISSUE TITLE
After tournament is deleted you should get back to Archived tournament list

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#114]
Open Archived tournaments -> Delete a tournament 

- [x] #201 Redirect user after deleting tournament to the archived tournament

- [x] #202 Fix test DeletePostAction_ExistingTournament_TournamentIsDeleted

- [x] #203 Manual test if after deleting we will be redirected into archived

**AR:** You are redirected to Tournament list page
**ER:** You should be redirected to Archived tournaments page
