### ISSUE TITLE
Edit Day Off game in Play Off tournament

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#131]
Admin should be able to edit Day Off game in first round of PlayOff tournament.

Subtask:

- [x] #172 Add method to edit Day Off in PlayOff
- [x] #173 Add edit options to DayOff
- [x] #175 Test edit Day Off in PlayOff
