### ISSUE TITLE
Show game number in Schedule view

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#132]
Each game has a number. As a user I want number to be displayed along with game on Schedule page.

Subtasks:

- [x] #153 Edit schedule view for not palyOff game
- [x] #168 Edit schedule view for palyOff game
- [x] #154 UT show game number in schedule view
