### ISSUE TITLE
Simplify Division and Group selection on Manage teams

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#180]
As an user I want to have simplified workflow for adding new teams to the tournament so I won't spend a lot of time doing repetitive work.

AC:

- When there is only one group in selector - do not show it
- When there is only one division in selector - do not show it
- even if the selector is not shown correct value should be saved.

- [x] #185 Hide group selector

- [x] #186 Hide Division selector

- [x] #187 Save data

- [x] #207  Test adding new team to tournament
