### ISSUE TITLE
Number of games in Playoff doubled

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#209]
1. Create Playoff tournament
2. Add several teams clicking Save after each team
3. Go to Schedule

Subtasks:

- [x]  #230 Modify adding/removing games to schedule 
- [x] #231 Change corresponded test or write new
- [x] #232 Manual QA test
**AR:** Each game is repeated twice
