### ISSUE TITLE
Exception is thrown when user edits game time in playoff

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#219]
Create playoff > Add some teams > Set game time for any game

- [x] #238 - Reproduce all scenarious when exception is appeared
- [x] #239 - Fix exception
- [x] #263 - Add UTs to test the corresponding logic change
- [ ] #240 - Test changes and results
