### ISSUE TITLE
Clean up Player aggregate

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#266]
Domain level:
- Refactor PlayerRepository: change Add signature, remove IUnitOfWork accessor, call commit inside. (See https://github.com/VolleyManagement/volley-management/wiki/Design-Guidelines)
- Remove calls to UnitOfWork.Commit() when PlayerRepository is used.
- Remove TeamId property (refactor affected code)

Service level:
- update Create, Edit, Delete according to changes in Domain level. Rename Create to CreateBulk for collection input

UT level:
- ideally UTs should not change. Except places related to TeamId property.
- look carefully at existing tests - how they can be improved?

Subtask:
- [x] #271 Refactor PlayerRepository
- [x] #273 Remove TeamId property
- [x] #274 Update Create, Edit, Delete according to changes in Domain level.
- [x] #354 Make tests run again (even if they fail)
