### ISSUE TITLE
Clean up Teams aggregate

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#295]
Domain level:

1. Refactor TeamRepository: change Add signature, remove IUnitOfWork accessor, call commit inside. (See https://github.com/VolleyManagement/volley-management/wiki/Design-Guidelines)
2. Remove calls to UnitOfWork.Commit() when TeamRepository is used.
3. Add PlayerId value object
4. Implement invariant validation

Service level:

1. update Create, Delete according to changes in Domain level.
2. Edit method should change only simple attributes of the team.
3. Add methods ChangeCaptain, AddPlayers, RemovePlayers

UT level:

1. All changes to the service level should be covered by unit tests.
2. All specifications for Player and Team Features should be implemented and passing.

### Sub-tasks

- [x] #299 Domain level changes.

- [x] #300 Service level changes.

- [x] #298 Fix UT.

- [ ] #364 Implement specs for Team Features.
