### ISSUE TITLE
Fix UT for Team Aggregate.

### ISSUE THREAD

**Issue by Myroslavv** [VolleyManagement/volley-management#298]
Parent #295 

### Subtasks
- [x] #315 

- [x]  #323 Add test methods for new implemented methods in TeamService

- [ ] #351 Fix existing UTs.
- [x] #353  Add test for AddPlayers, RemovePlayers
