### ISSUE TITLE
Change Domain level for Teams aggregate.

### ISSUE THREAD

**Issue by Myroslavv** [VolleyManagement/volley-management#299]
Parent #295 

### Tasks:

- [x] Refactor TeamRepository: change Add signature, remove IUnitOfWork accessor, call commit inside. (See [Guideline](https://github.com/VolleyManagement/volley-management/wiki/Design-Guidelines)).

- [x] Remove calls to UnitOfWork.Commit() when TeamRepository is used.

- [x] Add PlayerId value object.

- [x] Implement invariant validation.
