### ISSUE TITLE
Change Service level for Teams aggregate.

### ISSUE THREAD

**Issue by Myroslavv** [VolleyManagement/volley-management#300]
Parent #295 

## Tasks:

- [x] update Create, Delete according to changes in Domain level.

- [x] Edit method should change only simple attributes of the team.

- [x] Add methods ChangeCaptain, AddPlayers, RemovePlayers.

## Subissues:

- [x] #319 Implement AddPlayers and RemovePlayers methods in TeamService
- [x] #320 Implement ChangeCaptain method in TeamService
