### ISSUE TITLE
Improve defect localization for Standings tests

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#60]
Instead of one "Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectStats" case we should have 4:

"Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectPointStats"

"Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectGamesStats"

"Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectSetsStats"

"Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectBallStats"

AC:

-[] Test should fail only if a specific part of calculation logic is broken. E.g. if we have defect in Games statistics calculation only this test should fail

- [x] #181 Test for Correct Point

- [x] #182 Test for Correct Games

- [x] #183 Test for Correct Sets

- [x] #184 Test for Correct Ball

- [x] Delete tests "Get(Pivot)Standings_GameResultsAllPossibleScores_CorrectStats"
