### ISSUE TITLE
Fix SonarLint warnings

### ISSUE THREAD

**Issue by sdiachen** [VolleyManagement/volley-management#96]
AC:

- Fix all warnings starting with "S", e.g. S101. Note: SA errors are out of scope
- Enable Threat Warnings as errors for Release configuration for all projects

- [x] #159 Fix SonarLint issues 1066, 1067, 1118, 1125, 1135
- [x] #160 Fix SonarLint issues 1144, 1200.
- [x] #161 Fix SonarLint issues 1301, 1309, 131, 134, 1449.
- [x] #162  Fix SonarLint issues 1450, 1481, 1541, 1939, 2360, 2933, 2971
- [x] #163 Fix SonarLint issues 2325.
- [x]  #164 Fix SonarLint issues 3235, 3240.
- [x] #165 Fix SonarLint issues 3242, 3246, 3253, 3717, 3776, 3875, 3881, 3897
- [x] #166 Fix SonarLint issues 3956
- [x] #167 Fix SonarLint issues 3928, 3963, 4035, 4058, 927
